"""add_model_name_to_runs

Revision ID: 1eb990de8c6e
Revises: 3f1a83e8b882
Create Date: 2026-01-15 17:23:25.353298

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "1eb990de8c6e"
down_revision: str | Sequence[str] | None = "3f1a83e8b882"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
