"""Initial tables

Revision ID: 325053741cd0
Revises: 86195f515103
Create Date: 2026-01-14 17:53:31.450401

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "325053741cd0"
down_revision: str | Sequence[str] | None = "86195f515103"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
