"""add_model_name_to_runs

Revision ID: 3f1a83e8b882
Revises: f34b888dfd62
Create Date: 2026-01-15 17:21:04.032186

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "3f1a83e8b882"
down_revision: str | Sequence[str] | None = "f34b888dfd62"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
