"""Initial tables

Revision ID: 86195f515103
Revises:
Create Date: 2026-01-14 17:52:02.994441

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "86195f515103"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
