"""Add finished_at to runs

Revision ID: a32d7e176b23
Revises: 92a58f1798c6
Create Date: 2026-01-14 19:19:42.701252

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a32d7e176b23"
down_revision: str | Sequence[str] | None = "92a58f1798c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluation_runs", sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluation_runs", "finished_at")
    # ### end Alembic commands ###
